
<script>
	import { composeTransitions } from "$lib/custom-svelte-transitions/transition-composition/compose-transitions";
	import { fade, slide } from "svelte/transition";


    const array = $state([
    {
        name: 'One',
        isDown: false
    },
    {
        name: 'Two',
        isDown: false
    }]);

    // target effect -
    // 1. Create Space for movement of element (in - slideIn, out - nothing (just delay the first transition)) 
    // 2. Fade (in - fadeIn, out - fadeOut (fade with reverse))
    // 3. Remove Space of Moved Element (in - nothing (element is already in space), out - slideOut (slide with reverse))

    // numbers:

    const inTransition = composeTransitions({
            reverse: false,
        }
        ,   
        [
            {
                transition:slide,
                params: {
                    delay: 0,
                    duration: 500,
                }
            }
            ,
            {
                transition:fade,
                params: {
                    delay: 500,
                    duration: 500,
                }
            }

        ]
    );

    const outTransition = composeTransitions({
            // reverse is useful for outTransitions as those are played already in reverse by default - this option effectively nullifies that. 
            reverse: true,
        }
        ,   
        [
            {
                // The reason i am listing slide first is because it overrides opacity css generated by fade. Even though start animating after
                transition:slide,
                params: {
                    // the slide effect will start later
                    delay: 1000,
                    duration: 500,
                    // slide is in by default, so we reverse it to be slide out (we use a reversed out transition so we need to mitigate that here)
                    reverse: true
                }
            }
            ,
            {
                transition:fade,
                params: {
                    delay: 500,
                    duration: 500,
                    reverse: true
                }
            }

        ]
    );
</script>

<main>
    <div class="lists-container">
        <ul>
            Up:
            {#each array as item, i}
                {#if !array[i].isDown}
                <li out:outTransition in:inTransition>
                    <button onclick={() => array[i].isDown = !array[i].isDown}>{item.name}</button>
                </li>
                {/if}
            {/each}
        </ul>
        <ul>
            Down:
            {#each array as item, i}
                {#if array[i].isDown}
                <li out:outTransition in:inTransition>
                    <button onclick={() => array[i].isDown = !array[i].isDown}>{item.name}</button>
                </li>
                {/if}
            {/each}
        </ul>
    </div>
</main>

<style>
    :root {
        --color1: rgb(241, 241, 241);
        --color2: #007AFF;
        --bg: #050505;
    }

    :global(body) {
        background-color: var(--bg);
        color: var(--color1);
        font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    }

    main {
        display: flex;          /* activate flexbox */
  justify-content: center;/* horizontal centering */
  align-items: center;    /* vertical centering */
    }
    
    button {
        background-color: var(--bg);
        border: 2px solid var(--color2);
        color: var(--color1);
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 5px;
        transition: background-color 0.3s, color 0.3s;
    }

    ul {
        display: flex;
        flex-direction: column;
        list-style-type: none;
        align-items: center;
    }

    .lists-container {
        display: flex;          
        justify-content: center;
        align-items: center;    
        flex-direction: column;
        border: #007AFF solid 2px;
        width: 500px;
    }
</style>